os:
  - linux

python:
 - "3.5"
 - "3.6"

env:
 - TOXENV=py36
 - TOXENV=py35

before_script:
  - echo "Before Script"
script:
  - echo "Testing...."
  - python -V
after_script:
  - echo "After Script.."

jobs:
  include:
    - stage: Deploy
      script: echo "Deploy...."
