os:
  - linux

language: python

jobs:
  include:
    - stage: Test with py35
      python: "3.5"
      env:
        - TOXENV=py35
      script:
        - python -V
        - echo "$TOXENV"
    - stage: Test with py36
      python: "3.6"
      env:
        - TOXENV=py36
      script:
        - python -V
        - echo "$TOXENV"
    - stage: Deploy
      script: echo "Deploy...."
