os:
  - linux

language: python

stages:
  - compile
  - test
  - deploy
env:
  - FOO=one
  - FOO=two
jobs:
  include:
    - stage: compile
      script: ./compile
    - stage: deploy
      script: ./deploy
