os:
  - linux

language: python

jobs:
  include:
    - stage: Testing
      before_script:
       - echo "Before Script"
      script: echo "Testing...."
      after_script:
       - echo "After Script.."
    - stage: Deploy
      script: echo "Deploy...."
      
